# dataset
dataset_name: 'pipeline_audio' # ['mnist','cifar10']
normal_class: [0]
known_outlier_class: [1]
ratio_known_normal: 0.3 # none
ratio_known_outlier: 0.9 # none
ratio_pollution: 0 #none
samples_sr: 22050
n_mfcc: 20
  #  n_known_normal = 300
  #  n_unlabeled_normal = n_normal - 300
  #  n_unlabeled_outlier = 0
  #  n_known_outlier = 200


# General setting
batch_size: 64
eta: 1
train: True

# training setting
epochs: 100
model_name: 'multi_CNN_base' # multi_CNN_base
lr: 0.001

# AE training setting
pretrain: False
ae_epochs: 50
ae_lr: 0.001